name: .NET

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore systemutviklerskolen-todo-app-backend
    - name: Build
      run: dotnet build systemutviklerskolen-todo-app-backend --no-restore

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: Restore frontend
      run: npm install 
      working-directory: systemutviklerskolen-todo-app-frontend/
    - name: Build frontend
      run: npm run build
      working-directory: systemutviklerskolen-todo-app-frontend/

